# Generated by Django 5.1 on 2024-12-07 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_per', models.CharField(default='100', max_length=3, verbose_name='Código perfil')),
                ('com_per', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comuna')),
                ('reg_per', models.CharField(blank=True, max_length=255, null=True, verbose_name='Región')),
                ('tel_per', models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono')),
                ('estado_capitulo', models.ManyToManyField(related_name='est_cap', through='cursos.EstadoCapitulo', to='cursos.capitulo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('visualizacion_capitulo', models.ManyToManyField(related_name='vis_cap', through='cursos.Visualizacion', to='cursos.capitulo')),
            ],
        ),
    ]
