# Generated by Django 5.1 on 2025-01-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo')),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje')),
            ],
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='cod_per',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='com_per',
            new_name='comuna',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='reg_per',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='tel_per',
            new_name='telefono',
        ),
    ]
