# Generated by Django 5.1 on 2024-12-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_perfil_comuna_alter_perfil_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='codigo_perfil',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='region',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='telefono',
        ),
        migrations.AddField(
            model_name='perfil',
            name='cod_per',
            field=models.CharField(default='100', max_length=3, verbose_name='Código perfil'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='com_per',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='reg_per',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tel_per',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono'),
        ),
    ]
