# Generated by Django 5.1 on 2025-01-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contacto_rename_cod_per_perfil_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='codigo',
            field=models.CharField(default='000', max_length=3, verbose_name='Código perfil'),
        ),
    ]
