# Generated by Django 5.1 on 2025-02-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_perfil_region_remove_perfil_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='verificado',
            field=models.BooleanField(default=False, verbose_name='Verificado'),
        ),
    ]
