# Generated by Django 5.1 on 2025-02-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_perfil_pais_alter_perfil_tipo_organizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='descuento_creactiva',
            field=models.BooleanField(default=False, verbose_name='Descuento Creactiva'),
        ),
    ]
