# Generated by Django 5.1 on 2025-03-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_perfil_verificado_perfil_tipo_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_descuento',
            field=models.CharField(blank=True, choices=[('0', 'ESTÁNDAR'), ('1', 'ESTUDIANTE'), ('2', 'PUEBLO ORIGINARIO')], default='0', max_length=50, null=True, verbose_name='Tipo descuento'),
        ),
    ]
