# Generated by Django 5.1 on 2024-11-26 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id_cap', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cap', models.CharField(max_length=255)),
                ('des_cap', models.TextField()),
                ('lin_cap', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id_eti', models.AutoField(primary_key=True, serialize=False)),
                ('nom_eti', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialComplementario',
            fields=[
                ('id_mat', models.AutoField(primary_key=True, serialize=False)),
                ('nom_mat', models.CharField(max_length=255)),
                ('lin_mat', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_cur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cur', models.CharField(max_length=255)),
                ('des_cur', models.TextField()),
                ('id_cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='cursos.capitulo')),
                ('id_eti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='cursos.etiqueta')),
            ],
        ),
        migrations.AddField(
            model_name='capitulo',
            name='id_lin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='cursos.materialcomplementario'),
        ),
    ]
