# Generated by Django 5.1 on 2024-12-07 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('aut', models.AutoField(primary_key=True, serialize=False, verbose_name='ID autor')),
                ('nom_aut', models.CharField(max_length=255, verbose_name='Nombre autor')),
            ],
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('cap', models.AutoField(primary_key=True, serialize=False, verbose_name='ID capítulo')),
                ('nom_cap', models.CharField(max_length=255, verbose_name='Nombre capítulo')),
                ('dur_cap', models.IntegerField(verbose_name='Duración (minutos)')),
                ('des_cap', models.TextField(verbose_name='Descripción')),
                ('nin_cap', models.IntegerField(verbose_name='Número de actividades interactivas')),
                ('lin_cap', models.URLField(verbose_name='Link capítulo')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('eti', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Etiqueta')),
                ('nom_eti', models.CharField(max_length=50, verbose_name='Nombre etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('idi', models.AutoField(primary_key=True, serialize=False, verbose_name='ID idioma')),
                ('nom_idi', models.CharField(max_length=255, verbose_name='Nombre idioma')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialesComplementario',
            fields=[
                ('mat', models.AutoField(primary_key=True, serialize=False, verbose_name='ID material')),
                ('nom_mat', models.CharField(max_length=255, verbose_name='Nombre material')),
                ('lin_mat', models.URLField(verbose_name='Link material')),
            ],
        ),
        migrations.CreateModel(
            name='Visualizacion',
            fields=[
                ('vis', models.AutoField(primary_key=True, serialize=False, verbose_name='ID visualización')),
                ('fec_vis', models.DateTimeField(verbose_name='Última visualización')),
                ('min_vis', models.IntegerField(verbose_name='Minuto última visualización')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('cur', models.AutoField(primary_key=True, serialize=False, verbose_name='ID curso')),
                ('nom_cur', models.CharField(max_length=255, verbose_name='Nombre curso')),
                ('dec_cur', models.CharField(max_length=255, verbose_name='Descripción Corta')),
                ('del_cur', models.TextField(verbose_name='Descripción Larga')),
                ('aut', models.ManyToManyField(related_name='autores', to='cursos.autor', verbose_name='Autores')),
                ('cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='cursos.capitulo', verbose_name='Capítulo')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCapitulo',
            fields=[
                ('est_cap', models.AutoField(primary_key=True, serialize=False, verbose_name='ID estado capítulo')),
                ('estado_capitulo', models.IntegerField(verbose_name='Estado capítulo')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulo_est', to='cursos.capitulo', verbose_name='capitulos')),
            ],
        ),
    ]
