# Generated by Django 5.1 on 2024-12-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_capitulo_id_lin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='id_eti',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Etiqueta'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='nom_eti',
            field=models.CharField(max_length=50, verbose_name='Nombre etiqueta'),
        ),
    ]
