# Generated by Django 5.1 on 2024-12-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_etiqueta_id_eti_alter_etiqueta_nom_eti'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='num_cap',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número capítulo'),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='des_cap',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='id_cap',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID capítulo'),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='lin_cap',
            field=models.URLField(verbose_name='Link capítulo'),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='nom_cap',
            field=models.CharField(max_length=255, verbose_name='Nombre capítulo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='des_cur',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id_cur',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nom_cur',
            field=models.CharField(max_length=255, verbose_name='Nombre curso'),
        ),
        migrations.AlterField(
            model_name='materialcomplementario',
            name='id_mat',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID material'),
        ),
        migrations.AlterField(
            model_name='materialcomplementario',
            name='lin_mat',
            field=models.URLField(verbose_name='Link material'),
        ),
        migrations.AlterField(
            model_name='materialcomplementario',
            name='nom_mat',
            field=models.CharField(max_length=255, verbose_name='Nombre material'),
        ),
    ]
