# Generated by Django 5.1 on 2024-12-04 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_capitulo_num_cap_alter_capitulo_des_cap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='id_lin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='cursos.materialcomplementario', verbose_name='Material asociado'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id_cap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='cursos.capitulo', verbose_name='Capítulo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id_eti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='cursos.etiqueta', verbose_name='Etiqueta'),
        ),
    ]
