# Generated by Django 5.1 on 2024-12-22 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_capitulo_fir_cap_alter_capitulo_js_cap_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='cap',
            new_name='capitulos',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='dec_cur',
            new_name='desc_corta',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='del_cur',
            new_name='desc_larga',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='eti',
            new_name='etiquetas',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='idi',
            new_name='idiomas',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='nom_cur',
            new_name='nombre',
        ),
    ]
