# Generated by Django 5.1 on 2024-12-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_rename_cap_curso_capitulos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen_portada',
            field=models.CharField(max_length=255, null=True, verbose_name='Imagen portada'),
        ),
    ]
