# Generated by Django 5.1 on 2025-01-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_remove_curso_capitulos_capitulo_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='nom_aut',
            new_name='nombre_autor',
        ),
        migrations.RenameField(
            model_name='capitulo',
            old_name='des_cap',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='capitulo',
            old_name='dur_cap',
            new_name='duracion',
        ),
        migrations.RenameField(
            model_name='capitulo',
            old_name='fir_cap',
            new_name='first_frame',
        ),
        migrations.RenameField(
            model_name='capitulo',
            old_name='lin_cap',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='capitulo',
            old_name='mat',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='capitulo',
            old_name='nom_cap',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='capitulo',
            old_name='nin_cap',
            new_name='num_actividades',
        ),
        migrations.RenameField(
            model_name='capitulo',
            old_name='thu_cap',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='aut',
            new_name='autores',
        ),
        migrations.RenameField(
            model_name='estadocapitulo',
            old_name='est_cap',
            new_name='est',
        ),
        migrations.RenameField(
            model_name='etiqueta',
            old_name='nom_eti',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='idioma',
            old_name='nom_idi',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='materialescomplementario',
            old_name='nom_mat',
            new_name='nombre_material',
        ),
        migrations.RenameField(
            model_name='visualizacion',
            old_name='fec_vis',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='visualizacion',
            old_name='min_vis',
            new_name='minuto',
        ),
        migrations.RemoveField(
            model_name='materialescomplementario',
            name='lin_mat',
        ),
        migrations.AddField(
            model_name='materialescomplementario',
            name='link_material',
            field=models.CharField(max_length=255, null=True, verbose_name='Link material'),
        ),
    ]
