# Generated by Django 5.1 on 2025-01-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_rename_nom_aut_autor_nombre_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='numero',
            field=models.IntegerField(null=True, verbose_name='Número capítulo'),
        ),
    ]
