# Generated by Django 5.1 on 2025-01-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_capitulo_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='desc_corta',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripción Corta'),
        ),
    ]
