# Generated by Django 5.1 on 2025-01-09 19:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_alter_visualizacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualizacion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última visualización'),
        ),
    ]
