# Generated by Django 5.1 on 2025-01-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_alter_visualizacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualizacion',
            name='minuto',
            field=models.FloatField(verbose_name='Minuto última visualización'),
        ),
    ]
