# Generated by Django 5.1 on 2025-01-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_alter_visualizacion_minuto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocapitulo',
            name='estado_capitulo',
            field=models.IntegerField(choices=[(0, 'No visto'), (1, 'Visto'), (2, 'Terminado')], default=0, verbose_name='Estado capítulo'),
        ),
    ]
