# Generated by Django 5.1 on 2025-02-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0016_alter_estadocapitulo_estado_capitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='js_trailer',
            field=models.CharField(max_length=255, null=True, verbose_name='Link xml.js trailer'),
        ),
        migrations.AddField(
            model_name='curso',
            name='link_trailer',
            field=models.URLField(max_length=255, null=True, verbose_name='Link trailer'),
        ),
        migrations.AddField(
            model_name='curso',
            name='xml_trailer',
            field=models.CharField(max_length=255, null=True, verbose_name='Link xml trailer'),
        ),
    ]
