# Generated by Django 5.1 on 2025-02-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_curso_js_trailer_curso_link_trailer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='js_trailer',
            field=models.CharField(max_length=255, null=True, verbose_name='Xml.js trailer'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='xml_trailer',
            field=models.CharField(max_length=255, null=True, verbose_name='Xml trailer'),
        ),
    ]
