# Generated by Django 5.1 on 2025-02-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0018_alter_curso_js_trailer_alter_curso_xml_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='contenidos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
