# Generated by Django 5.1 on 2025-02-19 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0019_capitulo_contenidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='etiqueta_promocional',
            field=models.CharField(blank=True, default='0', max_length=1, null=True, verbose_name='Etiqueta promocional'),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='fecha_lanzamiento',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha lanzamiento'),
        ),
    ]
