# Generated by Django 5.1 on 2025-02-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0021_alter_capitulo_fecha_lanzamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='etiqueta_promocional',
            field=models.CharField(blank=True, choices=[('0', ''), ('1', 'ESTRENO'), ('2', 'PRÓXIMAMENTE')], default='0', max_length=1, null=True, verbose_name='Etiqueta promocional'),
        ),
    ]
