# Generated by Django 5.1 on 2025-02-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0023_curso_etiqueta_promocional_curso_fecha_lanzamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='fecha_lanzamiento',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha lanzamiento'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_lanzamiento',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha lanzamiento'),
        ),
    ]
