# Generated by Django 5.1 on 2025-02-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0024_alter_capitulo_fecha_lanzamiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='js_trailer',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='link_trailer',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='xml_trailer',
        ),
        migrations.AddField(
            model_name='capitulo',
            name='js_trailer',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Xml.js trailer'),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='link_trailer',
            field=models.URLField(default=None, max_length=255, null=True, verbose_name='Link trailer'),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='xml_trailer',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Xml trailer'),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='etiqueta_promocional',
            field=models.CharField(blank=True, choices=[('0', '--- NINGUNO ---'), ('1', 'ESTRENO'), ('2', 'PRÓXIMAMENTE'), ('3', 'SIN LANZAMIENTO')], default='0', max_length=1, null=True, verbose_name='Etiqueta promocional'),
        ),
    ]
