# Generated by Django 5.1 on 2025-02-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0025_remove_curso_js_trailer_remove_curso_link_trailer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='js_trailer',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Xml.js trailer'),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='link_trailer',
            field=models.URLField(blank=True, default=None, max_length=255, null=True, verbose_name='Link trailer'),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='xml_trailer',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Xml trailer'),
        ),
    ]
