# Generated by Django 5.1 on 2025-03-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0026_alter_capitulo_js_trailer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='descriptor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre autor'),
        ),
    ]
