# Generated by Django 5.1 on 2025-03-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0027_alter_capitulo_link_alter_capitulo_link_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='descriptor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descriptor'),
        ),
    ]
