# Generated by Django 5.1 on 2024-12-07 23:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('sus', models.AutoField(primary_key=True, serialize=False, verbose_name='ID suscripción')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha inicio')),
                ('fehca_termino', models.DateTimeField(null=True, verbose_name='Fecha término')),
                ('monto', models.IntegerField(null=True, verbose_name='Monto')),
                ('numero_usuarios', models.IntegerField(default=1, verbose_name='Número usuarios')),
                ('codigo_validacion', models.CharField(max_length=255, null=True, verbose_name='Código validación')),
                ('estado_suscripcion', models.IntegerField(default=0, verbose_name='Estado suscripción')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilSuscripcion',
            fields=[
                ('usu_sus', models.AutoField(primary_key=True, serialize=False, verbose_name='ID suscripciones perfiles')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_sus', to='main.perfil', verbose_name='Perfil suscripción')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion_det_per', to='suscripciones.suscripcion', verbose_name='Suscripción Detalle Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='CursosSuscripcion',
            fields=[
                ('cur_sus', models.AutoField(primary_key=True, serialize=False, verbose_name='ID cursos suscripciones')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_sus', to='cursos.curso', verbose_name='Curso suscrito')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion_det_cur', to='suscripciones.suscripcion', verbose_name='Suscripción Detalle Curso')),
            ],
        ),
    ]
