# Generated by Django 5.1 on 2025-01-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudOrganizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido')),
            ],
        ),
    ]
