# Generated by Django 5.1 on 2025-01-14 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0002_solicitudorganizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudorganizacion',
            name='cursos',
            field=models.JSONField(blank=True, default=None, verbose_name='Cursos'),
        ),
        migrations.AddField(
            model_name='solicitudorganizacion',
            name='mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje'),
        ),
        migrations.AddField(
            model_name='solicitudorganizacion',
            name='tipo_organizacion',
            field=models.CharField(choices=[('1', 'Empresa'), ('2', 'Organización de la Sociedad Civil'), ('3', 'Entidad fiscal')], default=None, max_length=33, verbose_name='Tipo organización'),
        ),
        migrations.AddField(
            model_name='solicitudorganizacion',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_org', to=settings.AUTH_USER_MODEL, verbose_name='Solicitud organización'),
        ),
    ]
