# Generated by Django 5.1 on 2025-01-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0004_solicitudorganizacion_comuna_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudorganizacion',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='solicitudorganizacion',
            name='nombre',
        ),
        migrations.AddField(
            model_name='solicitudorganizacion',
            name='nombre_organizacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre organización'),
        ),
        migrations.AddField(
            model_name='solicitudorganizacion',
            name='pais',
            field=models.CharField(default=None, max_length=2, verbose_name='País'),
        ),
    ]
