# Generated by Django 5.1 on 2025-01-23 23:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0006_rename_fehca_termino_suscripcion_fecha_termino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_termino',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Fecha término'),
        ),
    ]
