# Generated by Django 5.1 on 2025-01-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0008_alter_suscripcion_estado_suscripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscripcion',
            old_name='sus',
            new_name='id',
        ),
    ]
