# Generated by Django 5.1 on 2025-01-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0010_rename_cur_sus_cursossuscripcion_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, verbose_name='Nombre plan')),
                ('monto', models.IntegerField(null=True, verbose_name='Monto')),
            ],
        ),
    ]
