# Generated by Django 5.1 on 2025-01-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0011_planes'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='duracion',
            field=models.IntegerField(null=True, verbose_name='Duración'),
        ),
    ]
