# Generated by Django 5.1 on 2025-02-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0012_planes_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='estado_transbank',
            field=models.CharField(max_length=100, null=True, verbose_name='Estado Transbank'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='fecha_transbank',
            field=models.CharField(max_length=100, null=True, verbose_name='Fecha Transbank'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='tarjeta',
            field=models.CharField(max_length=10, null=True, verbose_name='Tarjeta Pago'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='token_ws',
            field=models.CharField(max_length=255, null=True, verbose_name='Token Webpay Service'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='monto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Monto'),
        ),
    ]
