# Generated by Django 5.1 on 2025-02-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0013_suscripcion_estado_transbank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='estado_suscripcion',
            field=models.CharField(default='0', max_length=1, verbose_name='Estado suscripción'),
        ),
    ]
