# Generated by Django 5.1 on 2025-02-10 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0014_alter_suscripcion_estado_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='suscripciones.planes', verbose_name='Plan'),
        ),
    ]
