# Generated by Django 5.1 on 2025-02-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0015_suscripcion_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='session_id_transbank',
            field=models.CharField(blank=True, max_length=61, null=True, verbose_name='Session ID Transbank'),
        ),
    ]
