# Generated by Django 5.1 on 2025-02-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0016_suscripcion_session_id_transbank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcion',
            name='estado_suscripcion',
        ),
        migrations.AddField(
            model_name='perfilsuscripcion',
            name='estado_suscripcion',
            field=models.CharField(default='0', max_length=1, verbose_name='Estado suscripción'),
        ),
    ]
