# Generated by Django 5.1 on 2025-02-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0017_remove_suscripcion_estado_suscripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudorganizacion',
            name='tipo_organizacion',
            field=models.CharField(choices=[('', 'Tipo de organización:'), ('1', 'Empresa'), ('2', 'Establecimiento educacional de enseñanza básica'), ('3', 'Establecimiento educacional de enseñanza media'), ('4', 'Establecimiento educacional de enseñanza básica y media'), ('5', 'Centro de Formación Técnica'), ('6', 'Instituto Profesional'), ('7', 'Universidad'), ('8', 'Fundación'), ('9', 'ONG'), ('10', 'Junta de vecinos'), ('11', 'Club deportivo'), ('12', 'Organización cultural'), ('13', 'Organización social'), ('14', 'Organización religiosa'), ('15', 'Organización política'), ('16', 'Organización ambiental'), ('17', 'Comunidad de pueblos originarios'), ('18', 'Otro')], default=None, max_length=33, verbose_name='Tipo organización'),
        ),
    ]
