# Generated by Django 5.1 on 2025-02-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0018_alter_solicitudorganizacion_tipo_organizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='monto',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Monto'),
        ),
    ]
