# Generated by Django 5.1 on 2025-02-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0019_alter_suscripcion_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilsuscripcion',
            name='descuento_creactiva',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Descuento Creactiva'),
        ),
    ]
