# Generated by Django 5.1 on 2025-02-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0020_perfilsuscripcion_descuento_creactiva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilsuscripcion',
            name='descuento_creactiva',
        ),
        migrations.AddField(
            model_name='perfilsuscripcion',
            name='boleta_entregada',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Boleta Entregada'),
        ),
    ]
