# Generated by Django 5.1 on 2025-02-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0021_remove_perfilsuscripcion_descuento_creactiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='plan_descuento',
            field=models.BooleanField(default=False, verbose_name='Es plan descuento'),
        ),
    ]
