# Generated by Django 5.1 on 2025-02-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0022_planes_plan_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción plan'),
        ),
    ]
