# Generated by Django 5.1 on 2025-02-16 23:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_perfil_descuento_creactiva'),
        ('suscripciones', '0023_planes_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código promocional')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creación')),
                ('fecha_caducidad', models.DateTimeField(blank=True, null=True, verbose_name='Fecha caducidad')),
                ('estado_codigo', models.CharField(default='1', max_length=1, verbose_name='Estado código')),
            ],
        ),
        migrations.AlterField(
            model_name='perfilsuscripcion',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_sus', to='main.perfil', verbose_name='ID Perfil'),
        ),
        migrations.AlterField(
            model_name='perfilsuscripcion',
            name='suscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion_det_per', to='suscripciones.suscripcion', verbose_name='ID Suscripción'),
        ),
        migrations.CreateModel(
            name='PerfilCodigo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID códigos perfiles')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suscripciones.codigopromocional', verbose_name='ID Código Promocional')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.perfil', verbose_name='ID Perfil')),
            ],
        ),
    ]
