# Generated by Django 5.1 on 2025-02-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0024_codigopromocional_alter_perfilsuscripcion_perfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcion',
            name='codigo_validacion',
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='codigo_promocional',
            field=models.CharField(blank=True, default='0', max_length=50, null=True, verbose_name='Código promocional'),
        ),
    ]
