# Generated by Django 5.1 on 2025-02-17 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0026_perfilcodigo_estado_uso_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilsuscripcion',
            name='codigo_promocional',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='suscripciones.codigopromocional', verbose_name='ID Código Promocional'),
        ),
        migrations.DeleteModel(
            name='PerfilCodigo',
        ),
    ]
