# Generated by Django 5.1 on 2025-02-17 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0027_perfilsuscripcion_codigo_promocional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilsuscripcion',
            name='codigo_promocional',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.CASCADE, to='suscripciones.codigopromocional', verbose_name='ID Código Promocional'),
        ),
    ]
