# Generated by Django 5.1 on 2025-02-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0029_perfilcodigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudorganizacion',
            name='comuna',
            field=models.CharField(blank=True, default=None, max_length=5, verbose_name='Comuna'),
        ),
    ]
