# Generated by Django 5.1 on 2025-02-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0030_alter_solicitudorganizacion_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudorganizacion',
            name='respondida',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Solicitud respondida'),
        ),
    ]
