# Generated by Django 5.1 on 2025-02-22 21:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0031_solicitudorganizacion_respondida'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudorganizacion',
            name='fecha_solicitud',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de solicitud'),
        ),
    ]
